apiVersion: v1
kind: Service
metadata:
  name: mcp-server
spec:
  selector: { app: mcp-server }
  ports:
    - name: http
      port: 4000
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-metrics
spec:
  selector: { app: mcp-server }
  ports:
    - name: metrics
      port: 8889
      targetPort: 8889
